"""
Contract generation command for CLI.

Reads a manifest and generates a typed API client for frontends.
Currently supports TypeScript output.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import click

from ..utils import load_manifest_file

_TS_HEADER = """/**
 * Auto-generated API client from manifest.
 * Generated by: mdb-engine codegen
 *
 * DO NOT EDIT — regenerate with:
 *   mdb-engine codegen {manifest_path} --target typescript --out {out_path}
 */

"""

_JSON_SCHEMA_TO_TS: dict[str, str] = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "array": "any[]",
    "object": "Record<string, any>",
}


def _ts_type(schema_type: str | None, prop_def: dict | None = None) -> str:
    """Map a JSON Schema type to a TypeScript type."""
    if not schema_type:
        return "any"
    base = _JSON_SCHEMA_TO_TS.get(schema_type, "any")
    if schema_type == "array" and prop_def:
        items = prop_def.get("items", {})
        item_type = _ts_type(items.get("type"))
        return f"{item_type}[]"
    if schema_type == "string" and prop_def and prop_def.get("enum"):
        return " | ".join(f'"{v}"' for v in prop_def["enum"])
    return base


def _interface_name(collection_name: str) -> str:
    """Convert collection name to PascalCase interface name."""
    parts = collection_name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts)


class TypeScriptGenerator:
    """Generate TypeScript API client from a manifest."""

    def __init__(self, manifest: dict[str, Any], base_url: str = "") -> None:
        self.manifest = manifest
        self.base_url = base_url
        self.lines: list[str] = []

    def generate(self) -> str:
        self.lines.append(
            _TS_HEADER.format(
                manifest_path="manifest.json",
                out_path="api-client.ts",
            )
        )

        self.lines.append(f'const BASE_URL = "{self.base_url}";\n')
        self.lines.append("type RequestOptions = { headers?: Record<string, string>; signal?: AbortSignal };\n")

        self._generate_fetch_helper()
        self.lines.append("")

        collections = self.manifest.get("collections", {})
        for name, config in collections.items():
            if not config.get("auto_crud", True):
                continue
            self._generate_interface(name, config)
            self._generate_functions(name, config)

        return "\n".join(self.lines)

    def _generate_fetch_helper(self) -> None:
        self.lines.append("""async function apiFetch<T>(
  path: string,
  options: RequestInit & RequestOptions = {},
): Promise<T> {
  const { headers: extraHeaders, ...rest } = options;
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json", ...extraHeaders },
    ...rest,
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => res.statusText);
    throw new Error(`API ${res.status}: ${detail}`);
  }
  return res.json();
}""")

    def _generate_interface(self, name: str, config: dict) -> None:
        iface = _interface_name(name)
        schema = config.get("schema", {})
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))

        self.lines.append(f"\n// ── {name} ────────────────────────────────────\n")
        self.lines.append(f"export interface {iface} {{")
        self.lines.append("  _id: string;")
        self.lines.append("  created_at?: string;")
        self.lines.append("  updated_at?: string;")

        for prop_name, prop_def in properties.items():
            ts_type = _ts_type(prop_def.get("type"), prop_def)
            optional = "" if prop_name in required else "?"
            self.lines.append(f"  {prop_name}{optional}: {ts_type};")

        self.lines.append("}\n")

        create_iface = f"{iface}Create"
        self.lines.append(f"export type {create_iface} = Omit<{iface}, '_id' | 'created_at' | 'updated_at'>;\n")

    def _generate_functions(self, name: str, config: dict) -> None:
        iface = _interface_name(name)
        prefix = f"/api/{name}"
        read_only = config.get("read_only", False)

        scopes = list(config.get("scopes", {}).keys())
        scope_type = " | ".join(f'"{s}"' for s in scopes) if scopes else "string"
        scope_param = f"scope?: {scope_type}" if scopes else "scope?: string"

        self.lines.append(f"export async function list{iface}s(params?: {{")
        self.lines.append(f"  {scope_param};")
        self.lines.append("  limit?: number;")
        self.lines.append("  skip?: number;")
        self.lines.append("  sort?: string;")
        self.lines.append(f"}}): Promise<{iface}[]> {{")
        self.lines.append("  const qs = new URLSearchParams();")
        self.lines.append('  if (params?.scope) qs.set("scope", params.scope);')
        self.lines.append('  if (params?.limit) qs.set("limit", String(params.limit));')
        self.lines.append('  if (params?.skip) qs.set("skip", String(params.skip));')
        self.lines.append('  if (params?.sort) qs.set("sort", params.sort);')
        self.lines.append('  const query = qs.toString() ? `?${qs}` : "";')
        self.lines.append(f"  return apiFetch(`{prefix}${{query}}`);")
        self.lines.append("}\n")

        self.lines.append(f"export async function get{iface}(id: string): Promise<{iface}> {{")
        self.lines.append(f"  return apiFetch(`{prefix}/${{id}}`);")
        self.lines.append("}\n")

        self.lines.append(f"export async function count{iface}s(scope?: string): Promise<number> {{")
        self.lines.append('  const qs = scope ? `?scope=${scope}` : "";')
        self.lines.append(f"  const res = await apiFetch<{{ count: number }}>(`{prefix}/_count${{qs}}`);")
        self.lines.append("  return res.count;")
        self.lines.append("}\n")

        if not read_only:
            self.lines.append(
                f"export async function create{iface}(data: {iface}Create): Promise<{{ data: {{ _id: string }} }}> {{"
            )
            self.lines.append(f'  return apiFetch(`{prefix}`, {{ method: "POST", body: JSON.stringify(data) }});')
            self.lines.append("}\n")

            ret_type = "Promise<{ data: { _id: string; modified: number } }>"
            self.lines.append(
                f"export async function update{iface}(id: string, data: Partial<{iface}Create>): {ret_type} {{"
            )
            self.lines.append(
                f'  return apiFetch(`{prefix}/${{id}}`, {{ method: "PATCH", body: JSON.stringify(data) }});'
            )
            self.lines.append("}\n")

            ret_type_del = "Promise<{ data: { _id: string; deleted: boolean } }>"
            self.lines.append(f"export async function delete{iface}(id: string): {ret_type_del} {{")
            self.lines.append(f'  return apiFetch(`{prefix}/${{id}}`, {{ method: "DELETE" }});')
            self.lines.append("}\n")


def generate_typescript(manifest: dict, base_url: str = "") -> str:
    """Public API for testing: generate TypeScript from manifest."""
    gen = TypeScriptGenerator(manifest, base_url)
    return gen.generate()


@click.command()
@click.argument("manifest_file", type=click.Path(exists=True, path_type=Path))
@click.option("--target", type=click.Choice(["typescript"]), default="typescript", help="Output target language")
@click.option("--out", "-o", type=click.Path(path_type=Path), default=None, help="Output file path")
@click.option("--base-url", default="", help="Base URL prefix for API calls")
def codegen(manifest_file: Path, target: str, out: Path | None, base_url: str) -> None:
    """Generate a typed API client from a manifest.

    MANIFEST_FILE: Path to manifest.json

    Examples:
        mdb-engine codegen manifest.json --target typescript --out api-client.ts
        mdb-engine codegen manifest.json -o src/api.ts --base-url /app1
    """
    try:
        manifest = load_manifest_file(manifest_file)
    except (FileNotFoundError, ValueError) as e:
        raise click.ClickException(str(e)) from e

    if target == "typescript":
        output = generate_typescript(manifest, base_url)
    else:
        raise click.ClickException(f"Unsupported target: {target}")

    if out:
        out.write_text(output)
        click.echo(click.style(f"Generated {target} client: {out}", fg="green"))
    else:
        click.echo(output)
